#!/bin/sh /etc/rc.common

START=99

start() {
	local dyndns=`uci get ddns.dyndns.enabled`
	local noip=`uci get ddns.noip.enabled`


	if [ "on" == $dyndns ]; then
    	ddns start dyndns
    fi
    if [ "on" == $noip ]; then
    	ddns start noip
    fi
}
