#! /bin/sh
test -n "$STAGING_DIR" && exec "$STAGING_DIR/../host/bin/bison" -y "$@"
exec '/home/tp-link-hm/work/ipf_plm/ipv6_three_moed_merge/iplatform/board/model_mtk_mt76xx/gplcode/staging_dir/host/bin/bison' -y "$@"
