#!/bin/sh

. /usr/lib/ddns/dynamic_dns_functions.sh

[ "$INTERFACE" == "lan" ] && exit 0

if [ "$ACTION" = "ifup" ]; then
	start_daemon_for_all_ddns_sections "$INTERFACE"
fi

if [ "$ACTION" = "ifdown" ]; then
	/usr/sbin/ddns stop "dyndns"
	/usr/sbin/ddns stop "noip"
fi


